---
# handlers file for roles/apache_0.0.1

    - name: Suppression du fichier index.html si appli non present
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent
      when: appli_enable != 'present'
